PROMPT:
  - KEY: "JIRA-TASK"
    LABEL: "Jira task ID (no-story)"
    DEFAULT_VALUE: "no-story"
  - KEY: "CHANGE"
    LABEL: "Type of change:"
    OPTIONS:
      - VALUE: "feature :sparkles:"
        DESC: "Add new feature"
      - VALUE: "fix :bug:"
        DESC: "A bug fix"
      - VALUE: "test :rotating_light:"
        DESC: "Adding missing tests or correcting ones"
      - VALUE: "style :lipstick:"
        DESC: "A code change to improve clean code"
      - VALUE: "build-ci :construction_worker:"
        DESC: "Changes on the build system or CI files"
      - VALUE: "refactor :hammer:"
        DESC: "A code change"
      - VALUE: "docs :books:"
        DESC: "Documentation only changes"
      - VALUE: "wip :construction:"
        DESC: "Work in progress"
      - VALUE: "code-review :ok_hand:"
        DESC: "Code review changes"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
TEMPLATE: "{{JIRA-TASK}} ({{CHANGE}}): {{MESSAGE}}"

